development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  min_messages: warning
  timeout: 5000
  database: place_development
  username: root
  password: root#admin
  socket: /var/run/mysqld/mysqld.sock
test: 
  adapter: mysql2
  encoding: utf8
  pool: 5
  min_messages: warning
  timeout: 5000
  database: place_test
  username: root
  password: root#admin
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 5
  min_messages: warning
  timeout: 5000
  database: place_production
  username: root
  password: lp5n4k3
  socket: /var/run/mysqld/mysqld.sock